
import turtle as t

def houseshort():
  t.pencolor('blue')
  t.fillcolor('blue')
  t.begin_fill()
  t.forward(300)
  t.left(90)
  t.forward(150)
  t.left(90)
  t.forward(300)
  t.left(90)
  t.forward(150)
  t.end_fill()
  t.left(180)
  
def roofshort():
  t.penup()
  t.goto(0,150)
  t.pendown()
  t.pencolor("red")
  t.fillcolor("red")
  t.begin_fill()
  t.right(60)
  t.forward(173)
  t.right(60)
  t.forward(173)
  t.right(150)
  t.forward(300)
  t.end_fill()

def window1short():  
  t.penup()
  t.goto(70,60)
  t.pendown()
  t.pencolor('grey')
  t.fillcolor('grey')
  t.begin_fill()
  t.forward(40)
  t.right(90)
  t.forward(40)
  t.right(90)
  t.forward(40)
  t.right(90)
  t.forward(40)
  t.right(90)
  t.end_fill()

def window2short():
  t.penup()
  t.goto(270,60)
  t.pendown()
  t.pencolor('grey')
  t.fillcolor('grey')
  t.begin_fill()
  t.forward(40)
  t.right(90)
  t.forward(40)
  t.right(90)
  t.forward(40)
  t.right(90)
  t.forward(40)
  t.right(90)
  t.end_fill()

def doorshort():
  t.penup()
  t.goto(170,0)
  t.pendown()
  t.pencolor('brown')
  t.fillcolor('brown')
  t.begin_fill()
  t.forward(40)
  t.right(90)
  t.forward(90)
  t.right(90)
  t.forward(40)
  t.right(90)
  t.forward(90)
  t.right(90)
  t.end_fill()

def main():
  houseshort()
  roofshort()
  window1short()
  window2short()
  doorshort()
  
main()