import turtle

def window(side: int):
    turtle.fillcolor("light grey")
    turtle.begin_fill()
    turtle.setheading(0)
    turtle.forward(side)
    turtle.right(90)
    turtle.forward(side)
    turtle.right(90)
    turtle.forward(side)
    turtle.right(90)
    turtle.forward(side)
    turtle.end_fill()

def tallhouse():
    # Rectangle
    turtle.left(90)
    turtle.fillcolor("green")
    turtle.begin_fill()
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(150)
    turtle.end_fill()

    turtle.fillcolor("brown")
    turtle.penup()
    turtle.left(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.pendown()
    turtle.begin_fill()
    turtle.left(120)
    turtle.forward(150)
    turtle.left(120)
    turtle.forward(150)
    turtle.left(120)
    turtle.forward(150)
    turtle.end_fill()

    turtle.penup()
    turtle.setheading(-90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(65)
    turtle.pendown()
    turtle.fillcolor("yellow")
    turtle.begin_fill()
    turtle.setheading(180)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(60)
    turtle.end_fill()

    turtle.penup()
    turtle.setheading(180)
    turtle.forward(85)
    turtle.right(90)
    turtle.forward(175)
    turtle.right(90)
    turtle.forward(20)
    turtle.pendown()
    window(30)
    turtle.penup()
    turtle.right(90)
    turtle.forward(40)
    turtle.pendown()
    window(30)
    turtle.penup()
    turtle.right(90)
    turtle.forward(40)
    turtle.pendown()
    window(30)

    turtle.penup()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(150)
    turtle.right(180)
    turtle.forward(20)
    turtle.pendown()

    window(30)
    turtle.penup()
    turtle.right(90)
    turtle.forward(40)
    turtle.pendown()
    window(30)
    turtle.penup()
    turtle.right(90)
    turtle.forward(40)
    turtle.pendown()
    window(30)
    
    turtle.penup()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(150)
    turtle.right(180)
    turtle.forward(20)
    turtle.pendown()

    window(30)
    turtle.penup()
    turtle.right(90)
    turtle.forward(80)
    turtle.pendown()
    window(30)

    turtle.done()
tallhouse()